<Project Sdk="MSTest.Sdk/4.0.1">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>HE_WrapperStandard_Tests</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HE WrapperStandard\HE WrapperStandard.csproj" />
  </ItemGroup>

</Project>
