<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoNets\CryptoNets.csproj" />
    <ProjectReference Include="..\HE WrapperStandard Tests\HE WrapperStandard Tests.csproj" />
  </ItemGroup>

</Project>
